Replace Logos and Remove Unnecessary Files
KSDHRVN/gino-lp pull request #31
Opened 2022-06-20 02:27 UTC by phelanksd

[Replace Logos and Remove Unnecessary Files

2022-06-20 04:26 UTC, buinhansinh commented
@yosiyuki  could you review? For <link rel="mask-icon" , we don't have the svg file , so just keeps the old icon there.

2022-06-20 07:59 UTC, yosiyuki commented
@ttmthanh Please review

2022-06-20 08:03 UTC, yosiyuki commented
@phelanksd Sorry for misunderstanding. Please update following image

![Screen Shot 2022-06-20 at 15 02 13](https://user-images.githubusercontent.com/338138/174554267-6fec04a0-9dad-4d76-a29c-f34175f5efb5.png)

2022-06-20 08:36 UTC, phelanksd commented
> Hi Yosiyuki, Please checkout branch Ticket-23_Replace_logo_and_remove_unnecessary_files and check again! This logo was updated.

![image](https://user-images.githubusercontent.com/106941237/174560312-34e9e530-1120-4774-a8a8-f02410d60bed.png)

2022-06-22 02:59 UTC, buinhansinh commented
@yosiyuki @ttmthanh  is there any problem with this pull request?

2022-06-22 03:14 UTC, yosiyuki requested changes
1. Please rename `src/images/logo_talent_header-asi.png` and `src/images/logo_talent-asi.png` . They looks typo in filename
2. Changing header is not in this task's request.
![Screen Shot 2022-06-22 at 10 10 15](https://user-images.githubusercontent.com/338138/174935572-cf1c5fe1-1006-4da2-8003-f6c92240a15a.png)

2022-06-22 03:30 UTC, buinhansinh commented
@yosiyuki 
1. "src/images/logo_talent-asi.png" will be renamed to "src/images/logo.png" -> is this ok?
2. The changes will be reverted.

2022-06-22 08:27 UTC, buinhansinh commented
@yosiyuki @ttmthanh  could you review again? Thanks

2022-06-22 10:26 UTC, ttmthanh commented
I think this picture (src/images/favicon/apple-touch-icon.png) should have white background because if transparent, it look ugly
- Transparent background
![image](https://user-images.githubusercontent.com/22828586/175006777-fadacf80-8358-4785-ab18-d9b1c8f8c305.png)
- White background
![image](https://user-images.githubusercontent.com/22828586/175006915-4551f6e3-0090-4841-abe3-e852d4828cc4.png)

2022-06-22 10:40 UTC, yosiyuki commented on en/index.html
> +            <a href="#" class="mx-4 items-center basis-1/5 flex">
I think better to have link to Google crawler

2022-06-22 18:11 UTC, ttmthanh requested changes

2022-06-22 18:11 UTC, ttmthanh commented on en/index.html
>                <h1 class="font-semibold text-[20px] md:text-[28px]">TalentAsiaJobs</h1>
Why you change this in this file, `index.html` and `vn/index.html`? [line:90]

2022-06-23 01:56 UTC, buinhansinh commented
@ttmthanh @yosiyuki  please check it again. Thanks

2022-06-23 09:27 UTC, ttmthanh approved these changes

2022-06-24 02:21 UTC, yosiyuki approved these changes

2022-06-24 02:23 UTC, yosiyuki commented
@buinhansinh Please deploy or assign to deploy this update.

1. Ask Horioka-san how to ftp access to server
2. Based on difference https://github.com/KSDHRVN/gino-lp/pull/31/files update files on server
3. Merge PR

2022-06-24 03:03 UTC, buinhansinh commented
@yosiyuki can we deploy this branch to server? Or we just deploy the changes only?

2022-06-24 16:18 UTC, buinhansinh requested changes
The image size is quite big compared to its size, this heavily affects the performance of webpage on mobile. Please optimize the image size.

2022-07-01 04:52 UTC, buinhansinh approved these changes

2022-07-01 04:53 UTC, merged