ref#5 create section introduction consultans
KSDHRVN/gino-lp pull request #7
Opened 2022-05-31 08:11 UTC by ttmthanh

Result:
1. PC
![image](https://user-images.githubusercontent.com/22828586/171125182-10267088-9865-4bad-86c4-eb0174d82756.png)
2. Mobile
![image](https://user-images.githubusercontent.com/22828586/171125220-9b0bea04-40b1-4c60-9832-301d04762af8.png)

2022-06-01 09:12 UTC, yosiyuki requested changes
1. Please make image smaller as view size
2. We don't need 2 uyen pics

2022-06-01 09:12 UTC, yosiyuki commented on index.html
> +                <button href="https://www.facebook.com/profile.php?id=100051502774248" class="text-[14px] md:text-[18px] transition-all ease-linear delay-0 hover:-translate-y-1 hover:scale-110 durati
You can't set href in `<a href >`

2022-06-03 09:46 UTC, yosiyuki commented on index.html
>          <span class="text-white px-4">Copyright © 2020 KOSAIDO BUSINESS SUPPORT CO., LTD. All Rights Reserved</span>
Please update 2020 -> 2022

2022-06-06 08:41 UTC, ttmthanh commented on index.html
>          <span class="text-white px-4">Copyright © 2020 KOSAIDO BUSINESS SUPPORT CO., LTD. All Rights Reserved</span>
I updated again

2022-06-06 15:49 UTC, yosiyuki approved these changes

2022-06-06 15:49 UTC, merged